In [13]:
%load_ext autoreload
%autoreload 2

In [11]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import pandas as pd
from src.poly_reg import model_county
from src.poly_reg import model_state
from src.data_import import nyt
import src.data_import as di

plt.style.use('ggplot')
font = {'weight' : 'bold',
        'size'   : 18}

plt.rc('font', **font)

In [32]:
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', None)

df = di.extract_election()

In [33]:
cadf = df[df['state'] == 'California']

In [34]:
len(cadf)

58

In [48]:
counties_df = pd.read_csv("./data/raw/County Physical.csv", sep='\t')

In [53]:
counties_df[counties_df['State'] == 'CA']

,Sort,State,FIPS,County,Seat,Pop,Land area km,Land area mi,Water area km,Water area mi,Total area km,Total area mi,Lat,Long
186,187,CA,6001,Alameda,Oakland,"1,510,271","1,914.046",739.017,213.185,82.311,"2,127.231",821.328,37.648081,–121.913304
187,188,CA,6003,Alpine,Markleeville,"1,175","1,912.272",738.332,12.557,4.848,"1,924.829",743.180,38.617610,–119.798999
188,189,CA,6005,Amador,Jackson,"38,091","1,539.963",594.583,29.457,11.373,"1,569.420",605.956,38.443550,–120.653856
189,190,CA,6007,Butte,Oroville,"220,000","4,238.423","1,636.464",105.326,40.667,"4,343.749","1,677.131",39.665959,–121.601919
190,191,CA,6009,Calaveras,San Andreas,"45,578","2,641.820","1,020.012",43.810,16.915,"2,685.630","1,036.927",38.187844,–120.555115
191,192,CA,6011,Colusa,Colusa,"21,419","2,980.379","1,150.731",14.581,5.630,"2,994.960","1,156.361",39.177739,–122.237563
192,193,CA,6013,Contra Costa,Martinez,"1,049,025","1,854.269",715.937,227.485,87.833,"2,081.754",803.770,37.919479,–121.951543
193,194,CA,6015,Del Norte,Crescent City,"28,610","2,606.494","1,006.373",578.526,223.370,"3,185.020","1,229.743",41.749903,–123.980998
194,195,CA,6017,El Dorado,Placerville,"181,058","4,423.397","1,707.883",203.243,78.473,"4,626.640","1,786.356",38.785532,–120.534398
195,196,CA,6019,Fresno,Fresno,"930,450","15,431.126","5,957.991",137.816,53.211,"15,568.942","6,011.202",36.761006,–119.655019
196,197,CA,6021,Glenn,Willows,"28,122","3,403.107","1,313.947",33.750,13.031,"3,436.857","1,326.978",39.602546,–122.401700
197,198,CA,6023,Humboldt,Eureka,"134,623","9,241.045","3,567.987","1,254.256",484.271,"10,495.301","4,052.258",40.706673,–123.925818
198,199,CA,6025,Imperial,El Centro,"174,528","10,817.353","4,176.603",790.248,305.116,"11,607.600","4,481.719",33.040816,–115.355395
199,200,CA,6027,Inyo,Independence,"18,546","26,368.354","10,180.879",119.208,46.026,"26,487.562","10,226.905",36.561977,–117.403927
200,201,CA,6029,Kern,Bakersfield,"839,631","21,061.565","8,131.916",79.577,30.725,"21,141.142","8,162.641",35.346629,–118.729506
201,202,CA,6031,Kings,Hanford,"152,982","3,598.582","1,389.420",5.469,2.111,"3,604.051","1,391.531",36.072478,–119.815530
202,203,CA,6033,Lake,Lakeport,"64,665","3,254.228","1,256.464",188.962,72.959,"3,443.190","1,329.423",39.094802,–122.746757
203,204,CA,6035,Lassen,Susanville,"34,895","11,761.612","4,541.184",463.441,178.935,"12,225.053","4,720.119",40.721089,–120.629931
204,205,CA,6037,Los Angeles,Los Angeles,"9,818,605","10,509.870","4,057.884","1,795.013",693.058,"12,304.883","4,750.942",34.196398,–118.261862
205,206,CA,6039,Madera,Madera,"150,865","5,534.983","2,137.069",41.958,16.200,"5,576.940","2,153.269",37.210039,–119.749852
206,207,CA,6041,Marin,San Rafael,"252,409","1,347.586",520.306,797.420,307.886,"2,145.006",828.192,38.051817,–122.745974
207,208,CA,6043,Mariposa,Mariposa,"18,251","3,752.417","1,448.816",36.271,14.004,"3,788.688","1,462.820",37.570034,–119.912860
208,209,CA,6045,Mendocino,Ukiah,"87,841","9,081.386","3,506.343",962.953,371.798,"10,044.339","3,878.141",39.432388,–123.442881
209,210,CA,6047,Merced,Merced,"255,793","5,011.555","1,934.972",112.760,43.537,"5,124.315","1,978.509",37.194806,–120.722802
210,211,CA,6049,Modoc,Alturas,"9,686","10,146.977","3,917.770",739.774,285.629,"10,886.752","4,203.399",41.592919,–120.718370
211,212,CA,6051,Mono,Bridgeport,"14,202","7,896.827","3,048.982",214.695,82.894,"8,111.523","3,131.876",37.915836,–118.875167
212,213,CA,6053,Monterey,Salinas,"415,057","8,496.703","3,280.595","1,270.714",490.626,"9,767.417","3,771.221",36.240107,–121.315573
213,214,CA,6055,Napa,Napa,"136,484","1,938.247",748.362,104.169,40.220,"2,042.417",788.582,38.507351,–122.325995
214,215,CA,6057,Nevada,Nevada City,"98,764","2,480.617",957.772,41.515,16.029,"2,522.132",973.801,39.295191,–120.773446
215,216,CA,6059,Orange,Santa Ana,"3,010,232","2,047.561",790.568,407.917,157.498,"2,455.478",948.066,33.675687,–117.777207
216,217,CA,6061,Placer,Auburn,"348,432","3,644.136","1,407.009",247.205,95.447,"3,891.341","1,502.456",39.062032,–120.722718
217,218,CA,6063,Plumas,Quincy,"20,007","6,612.351","2,553.043",156.395,60.385,"6,768.746","2,613.428",39.995170,–120.829516
218,219,CA,6065,Riverside,Riverside,"2,189,641","18,664.697","7,206.480",251.073,96.940,"18,915.770","7,303.420",33.729828,–116.002239
219,220,CA,6067,Sacramento,Sacramento,"1,418,788","2,498.416",964.644,76.077,29.374,"2,574.493",994.018,38.450011,–121.340441
220,221,CA,6069,San Benito,Hollister,"55,269","3,596.742","1,388.710",4.555,1.759,"3,601.297","1,390.469",36.610702,–121.085296
221,222,CA,6071,San Bernardino,San Bernardino,"2,035,210","51,947.230","20,056.938",124.028,47.888,"52,071.258","20,104.826",34.857220,–116.181197
222,223,CA,6073,San Diego,San Diego,"3,095,313","10,895.121","4,206.630",826.348,319.055,"11,721.469","4,525.685",33.023604,–116.776117
223,224,CA,6075,San Francisco,San Francisco,"805,235",121.400,46.873,479.190,185.016,600.590,231.889,37.727239,–123.032229
224,225,CA,6077,San Joaquin,Stockton,"685,306","3,603.506","1,391.322",91.109,35.177,"3,694.615","1,426.499",37.935034,–121.272237
225,226,CA,6079,San Luis Obispo,San Luis Obispo,"269,637","8,543.248","3,298.567",820.975,316.980,"9,364.223","3,615.547",35.385227,–120.447540
226,227,CA,6081,San Mateo,Redwood City,"718,451","1,161.372",448.408,757.704,292.551,"1,919.076",740.959,37.414664,–122.371542
227,228,CA,6083,Santa Barbara,Santa Barbara,"423,895","7,083.838","2,735.085","2,729.829","1,053.993","9,813.667","3,789.078",34.537378,–120.038485
228,229,CA,6085,Santa Clara,San Jose,"1,781,642","3,341.343","1,290.100",36.175,13.967,"3,377.518","1,304.067",37.220777,–121.690622
229,230,CA,6087,Santa Cruz,Santa Cruz,"262,382","1,152.986",445.170,419.569,161.996,"1,572.555",607.166,37.012488,–122.007205
230,231,CA,6089,Shasta,Redding,"177,223","9,778.247","3,775.402",186.531,72.020,"9,964.778","3,847.422",40.760522,–122.043550
231,232,CA,6091,Sierra,Downieville,"3,240","2,468.814",953.214,23.299,8.996,"2,492.113",962.210,39.576925,–120.521993
232,233,CA,6093,Siskiyou,Yreka,"44,900","16,259.652","6,277.887",179.889,69.456,"16,439.542","6,347.343",41.587986,–122.533287
233,234,CA,6095,Solano,Fairfield,"413,344","2,128.361",821.765,218.666,84.427,"2,347.027",906.192,38.267226,–121.939594
234,235,CA,6097,Sonoma,Santa Rosa,"483,878","4,081.430","1,575.849",497.530,192.098,"4,578.960","1,767.947",38.532574,–122.945194
235,236,CA,6099,Stanislaus,Modesto,"514,453","3,871.583","1,494.827",51.437,19.860,"3,923.020","1,514.687",37.562384,–121.002656
236,237,CA,6101,Sutter,Yuba City,"94,737","1,560.236",602.410,15.747,6.080,"1,575.983",608.490,39.035257,–121.702758
237,238,CA,6103,Tehama,Red Bluff,"63,463","7,639.710","2,949.709",32.276,12.462,"7,671.986","2,962.171",40.126156,–122.232276
238,239,CA,6105,Trinity,Weaverville,"13,786","8,234.230","3,179.254",73.408,28.343,"8,307.638","3,207.597",40.647724,–123.114404
239,240,CA,6107,Tulare,Visalia,"442,179","12,494.658","4,824.215",37.392,14.437,"12,532.050","4,838.652",36.230453,–118.780542
240,241,CA,6109,Tuolumne,Sonora,"55,365","5,752.063","2,220.884",138.684,53.546,"5,890.746","2,274.430",38.021451,–119.964708
241,242,CA,6111,Ventura,Ventura,"823,318","4,773.692","1,843.133",945.992,365.249,"5,719.684","2,208.382",34.358742,–119.133143
242,243,CA,6113,Yolo,Woodland,"200,849","2,628.032","1,014.689",22.969,8.868,"2,651.002","1,023.557",38.679268,–121.903178
243,244,CA,6115,Yuba,Marysville,"72,155","1,636.454",631.839,30.999,11.969,"1,667.453",643.808,39.270026,–121.344280

In [57]:
airports_df = pd.read_csv("./data/raw/Airports.csv")

In [58]:
airports_df

,airport,pax,domestic,international,lat,long
0,"Atlanta, GA (ATL)","50,685,574","44,763,207","5,922,367",33.640411,-84.419853
1,"Los Angeles, CA (LAX)","41,838,394","29,492,843","12,345,551",33.942791,-118.410042
2,"Chicago, IL (ORD)","38,723,494","32,326,627","6,396,867",41.978611,-87.904724
3,"Dallas/Fort Worth, TX (DFW)","31,944,822","27,870,888","4,073,934",32.897480,-97.040443
4,"Denver, CO (DEN)","30,184,026","28,905,065","1,278,961",39.849312,-104.673828
5,"New York, NY (JFK)","29,681,381","13,573,477","16,107,904",40.639801,-73.778900
6,"San Francisco, CA (SFO)","27,091,897","20,561,302","6,530,595",37.615223,-122.389977
7,"Las Vegas, NV (LAS)","23,536,326","21,785,184","1,751,142",36.213257,-115.194572
8,"Seattle, WA (SEA)","22,675,295","20,229,293","2,446,002",47.443546,-122.301659
9,"Charlotte, NC (CLT)","22,256,628","20,734,247","1,522,381",35.213890,-80.943054
10,"Orlando, FL (MCO)","21,706,032","18,872,581","2,833,451",28.429399,-81.308998
11,"Newark, NJ (EWR)","21,625,449","15,326,870","6,298,579",40.692501,-74.168701
12,"Phoenix, AZ (PHX)","21,597,513","20,574,818","1,022,695",33.434299,-112.012001
13,"Miami, FL (MIA)","20,747,454","10,296,343","10,451,111",25.793200,-80.290604
14,"Houston, TX (IAH)","19,678,502","14,615,953","5,062,549",29.984400,-95.341400
15,"Boston, MA (BOS)","18,810,204","15,391,163","3,419,041",42.366978,-71.022362
16,"Minneapolis, MN (MSP)","18,478,761","17,025,649","1,453,112",44.882000,-93.221802
17,"Detroit, MI (DTW)","17,119,842","15,364,985","1,754,857",42.212399,-83.353401
18,"Fort Lauderdale, FL (FLL)","15,903,280","12,380,941","3,522,339",26.072599,-80.152702
19,"New York, NY (LGA)","14,623,902","13,566,621","1,057,281",40.777199,-73.872597
20,"Philadelphia, PA (PHL)","14,324,174","12,553,714","1,770,460",39.871899,-75.241096
21,"Baltimore, MD (BWI)","13,237,599","12,707,397","530,202",39.175400,-76.668297
22,"Salt Lake City, UT (SLC)","11,664,659","11,222,360","442,299",40.788399,-111.977997
23,"Washington, DC (DCA)","11,543,328","11,365,632","177,696",38.852100,-77.037697
24,"San Diego, CA (SAN)","11,290,310","10,834,606","455,704",32.731770,-117.197624
25,"Chicago, IL (MDW)","11,170,533","10,766,291","404,242",41.785999,-87.752403
26,"Washington, DC (IAD)","11,077,634","7,320,099","3,757,535",38.944500,-77.455803
27,"Honolulu, HI (HNL)","10,096,176","7,430,649","2,665,527",21.320620,-157.924228
28,"Tampa, FL (TPA)","9,676,889","9,236,507","440,382",27.979168,-82.539337
29,"Portland, OR (PDX)","9,466,577","9,098,136","368,441",NaN,NaN
30,"Dallas, TX (DAL)","7,930,421","7,925,332","5,089",NaN,NaN
31,"St. Louis, MO (STL)","7,442,736","7,318,250","124,486",NaN,NaN
32,"Nashville, TN (BNA)","7,119,470","7,032,020","87,450",36.131687,-86.668823
33,"Austin, TX (AUS)","6,968,463","6,804,711","163,752",NaN,NaN
34,"Houston, TX (HOU)","6,762,375","6,311,099","451,276",NaN,NaN
35,"Oakland, CA (OAK)","6,558,080","6,181,543","376,537",NaN,NaN
36,"San Jose, CA (SJC)","6,246,641","5,817,959","428,682",NaN,NaN
37,"New Orleans, LA (MSY)","6,131,632","6,042,945","88,687",NaN,NaN
38,"Kansas City, MO (MCI)","5,801,816","5,768,646","33,170",NaN,NaN
39,"Raleigh/Durham, NC (RDU)","5,747,300","5,582,857","164,443",NaN,NaN
40,"Sacramento, CA (SMF)","5,455,439","5,343,355","112,084",NaN,NaN
41,"Santa Ana, CA (SNA)","5,132,119","4,997,835","134,284",33.678925,-117.862869
42,"San Antonio, TX (SAT)","4,489,909","4,298,517","191,392",29.384344,-98.618645
43,"Cleveland, OH (CLE)","4,481,845","4,393,355","88,490",NaN,NaN
44,"Indianapolis, IN (IND)","4,415,754","4,375,248","40,506",NaN,NaN
45,"Fort Myers, FL (RSW)","4,395,638","4,215,766","179,872",NaN,NaN
46,"Pittsburgh, PA (PIT)","4,373,044","4,247,683","125,361",NaN,NaN
47,"San Juan, PR (SJU)","4,187,182","3,742,098","445,084",NaN,NaN
48,"Cincinnati, OH (CVG)","3,816,634","3,684,585","132,049",39.053276,-84.663017
49,"Columbus, OH (CMH)","3,741,307","3,698,549","42,758",NaN,NaN
50,"Milwaukee, WI (MKE)","3,487,860","3,421,109","66,751",42.949890,-87.900414
51,"Kahului, HI (OGG)","3,437,781","3,257,548","180,233",NaN,NaN
52,"Hartford, CT (BDL)","3,177,578","3,092,331","85,247",NaN,NaN
53,"Palm Beach, FL (PBI)","3,132,368","3,053,733","78,635",NaN,NaN
54,"Jacksonville, FL (JAX)","2,726,987","2,716,631","10,356",NaN,NaN
55,"Anchorage, AK (ANC)","2,551,285","2,512,902","38,383",NaN,NaN
56,"Albuquerque, NM (ABQ)","2,481,815","2,478,864","2,951",NaN,NaN
57,"Burbank, CA (BUR)","2,464,652","2,464,496",156,NaN,NaN
58,"Buffalo, NY (BUF)","2,360,456","2,358,366","2,090",NaN,NaN
59,"Omaha, NE (OMA)","2,293,797","2,293,262",535,NaN,NaN
60,"Ontario, CA (ONT)","2,290,536","2,221,680","68,856",NaN,NaN
61,"Memphis, TN (MEM)","2,138,068","2,126,350","11,718",35.040031,-89.981873
62,"Reno, NV (RNO)","1,966,795","1,947,053","19,742",NaN,NaN
63,"Charleston, SC (CHS)","1,964,704","1,964,347",357,NaN,NaN
64,"Oklahoma City, OK (OKC)","1,955,646","1,955,339",307,NaN,NaN
65,"Providence, RI (PVD)","1,948,124","1,887,188","60,936",NaN,NaN
66,"Richmond, VA (RIC)","1,839,001","1,838,806",195,NaN,NaN
67,"Long Beach, CA (LGB)","1,832,716","1,832,702",14,NaN,NaN
68,"Boise, ID (BOI)","1,815,767","1,815,646",121,NaN,NaN
69,"Kona, HI (KOA)","1,767,192","1,694,751","72,441",NaN,NaN
70,"Louisville, KY (SDF)","1,716,244","1,716,039",205,NaN,NaN
71,"Norfolk, VA (ORF)","1,709,527","1,709,079",448,NaN,NaN
72,"Spokane, WA (GEG)","1,705,327","1,704,995",332,NaN,NaN
73,"Tucson, AZ (TUS)","1,687,514","1,685,121","2,393",32.116112,-110.941109
74,"Guam, TT (GUM)","1,613,194","162,278","1,450,916",NaN,NaN
75,"Lihue, HI (LIH)","1,523,987","1,499,557","24,430",NaN,NaN
76,"El Paso, TX (ELP)","1,489,944","1,471,413","18,531",NaN,NaN
77,"Sanford, FL (SFB)","1,426,695","1,294,624","132,071",NaN,NaN
78,"Grand Rapids, MI (GRR)","1,424,122","1,424,115",7,NaN,NaN
79,"Tulsa, OK (TUL)","1,408,217","1,408,059",158,NaN,NaN
80,"Albany, NY (ALB)","1,403,256","1,403,020",236,NaN,NaN
81,"Birmingham, AL (BHM)","1,384,367","1,383,936",431,NaN,NaN
82,"Des Moines, IA (DSM)","1,274,308","1,274,284",24,NaN,NaN
83,"Rochester, NY (ROC)","1,209,942","1,200,800","9,142",NaN,NaN
84,"Savannah, GA (SAV)","1,201,759","1,194,295","7,464",NaN,NaN
85,"Myrtle Beach, SC (MYR)","1,153,320","1,147,156","6,164",NaN,NaN
86,"Palm Springs, CA (PSP)","1,061,202","871,868","189,334",NaN,NaN
87,"Greer, SC (GSP)","1,057,127","1,057,036",91,NaN,NaN
88,"St. Petersburg, FL (PIE)","1,026,204","1,016,519","9,685",NaN,NaN
89,"Syracuse, NY (SYR)","1,018,246","1,009,733","8,513",NaN,NaN
90,"Little Rock, AR (LIT)","990,340","990,340",0,NaN,NaN
91,"Knoxville, TN (TYS)","974,671","974,431",240,NaN,NaN
92,"Manchester, NH (MHT)","971,803","971,779",24,NaN,NaN
93,"Madison, WI (MSN)","949,693","949,682",11,NaN,NaN
94,"Dayton, OH (DAY)","937,013","937,013",0,NaN,NaN
95,"Portland, ME (PWM)","926,403","925,958",445,NaN,NaN
96,"Greensboro/High Point, NC (GSO)","887,596","887,590",6,NaN,NaN
97,"Colorado Springs, CO (COS)","855,384","855,384",0,NaN,NaN
98,"Pensacola, FL (PNS)","850,373","850,292",81,NaN,NaN
99,"Wichita, KS (ICT)","808,055","808,028",27,NaN,NaN

In [64]:
import mpu

def intl_arrival_index(lat,lon):
    airports_df = pd.read_csv("./data/raw/Airports.csv")
    idx = 0
    airports = []
    for i, airport in airports_df.iterrows():
        print(type(airport))
        alat = airport['lat']
        alon = airport['lon']
        dist = mpu.haversine_distance((lat, lon), (alat, alon))
        print('{} is {} miles away').format(airport['airport'], dist)
        
intl_arrival_index(37.648081, -121.913304)

<class 'pandas.core.series.Series'>

AttributeError: 'Series' object has no attribute 'long'